language: python

python:
  - "3.6"

service:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - export APP_SETTINGS="project.config.TestingConfig"
  - export DATABASE_TEST_URL=postgresql://postgres:peter926@localhost/users_test
  - psql -c 'create database users_test;' -U postgres
  - python manage.py recreate_db

script:
  - coverage run manage.py cov  

after_success: coveralls
